trigger:
- main

variables:
  azureSubscription: '76554242-9749-4833-82ab-ba4cb890162e'
  functionAppName: 'cron-api'
  environmentName: 'cron-api'
  vmImageName: 'ubuntu-latest'
  webStorageName: 'cronweb'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: 'src/web'
    - task: Npm@1
      inputs:
        command: 'custom'
        workingDir: 'src/web'
        customCommand: 'run build'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'src/web/build'
        ArtifactName: 'web'
        publishLocation: 'Container'


- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentName)
    pool: 
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'web'
                downloadPath: '$(System.ArtifactsDirectory)'
            - task: AzureFileCopy@4
              inputs:
                SourcePath: '$(System.ArtifactsDirectory)/web/*'
                azureSubscription: '$(azureSubscription)'
                Destination: 'AzureBlob'
                storage: '$(webStorageName)'
                ContainerName: '$web'